apiVersion: apps/v1
kind: Deployment
metadata:
  name: app5
  labels:
    app: frontend1
spec:
  replicas: 2 # Fixed typo
  selector:
    matchLabels:
      app: frontend1
  template:
    metadata:
      labels:
        app: frontend1
    spec:
      containers:
        - name: app5
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80  # Fixed key name

---


apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

